version: "3.9"
services:
  ethereum-nextjs-app:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
  ethereum-nextjs-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      - ethereum-nextjs-app
networks:
  app-network:
    driver: bridge